# Coding a Linear Search Algorithm......

# Defiing the function.....
def Linear_Search(arr, key):
    count = 0 # Applying a counter variable.....
    for i in arr:
        if key == i: # Matching the key ......
            count += 1 # Incresing the counter value by 1
    # If the key is present then go to IF block or go to ELSE block !!!!!
    if count >= 1:
        return f'{key} is present {count} times'# Returing the final result
    else:
        return f'{key} is not there in the array.....' # Returing if there is not key present.....

# Calling the function......
lmt = int(input("Enter the limit: "))
arr = [] # Initializing empty list......
for i in range(1, lmt + 1):
    inp = int(input("Value: "))
    arr.append(inp) # Appending the values.......

key = int(input("Enter the key: "))
# Calling the linear search function.....
print(Linear_Search(arr, key))